# 1.  Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def function():
    return 5/0

try:
    function()
except ZeroDivisionError:
    print ("division by zero!")
except Exception:
    print ('Caught an exception')
finally:
    print ('In finally block for cleanup')

division by zero!
In finally block for cleanup


# 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [2]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentence_list = [(subject+" "+verb+" "+object) for subject in subjects for verb in verbs for object in objects]

for sentence in sentence_list:
    print(sentence)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# 3. Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

Practice of question no 3

In [88]:
import numpy as np
x = np.array([1,2,3,4,5])
N = 3
np.vander(x,N)


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [138]:
np.column_stack([x**(N-i-1) for i in range(N)])
#np.vander(x,increasing=True,N=3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]], dtype=int32)

In [125]:
van = np.array([1,2,4,6,8,10])
np.vander(van)

array([[     1,      1,      1,      1,      1,      1],
       [    32,     16,      8,      4,      2,      1],
       [  1024,    256,     64,     16,      4,      1],
       [  7776,   1296,    216,     36,      6,      1],
       [ 32768,   4096,    512,     64,      8,      1],
       [100000,  10000,   1000,    100,     10,      1]])

In [126]:
np.vander(van,increasing=True)

array([[     1,      1,      1,      1,      1,      1],
       [     1,      2,      4,      8,     16,     32],
       [     1,      4,     16,     64,    256,   1024],
       [     1,      6,     36,    216,   1296,   7776],
       [     1,      8,     64,    512,   4096,  32768],
       [     1,     10,    100,   1000,  10000, 100000]])

In [133]:
def vander_matrix(ipvector,n, increasing = False):
    if not increasing:
        mat= np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        mat = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    return mat


vector = np.array([1,2,3,4,5])
NoOfColumn = 3
op_matx_dec_order = vander_matrix(vector,NoOfColumn,False)
op_matx_inc_order = vander_matrix(vector,NoOfColumn,True)


print("---------------------------------------------------------------\n")

print("The input array is ", vector,"\n")
print("Number of columns in output matrix should be:",NoOfColumn,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")


vector = np.array([1,2,4,6,8,10])
NoOfColumn = 5
op_matx_dec_order = gen_vander_matrix(vector,NoOfColumn,False)
op_matx_inc_order = gen_vander_matrix(vector,NoOfColumn,True)


print("---------------------------------------------------------------\n")
print("The input array is:",vector,"\n")
print("Number of columns in output matrix should be:",NoOfColumn,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

---------------------------------------------------------------

The input array is  [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

---------------------------------------------------------------

The input array is: [ 1  2  4  6  8 10] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [  